### ISSUE TITLE
Cookie associated with a cross site resource

### ISSUE THREAD

**Issue by BradHN1** [massenergize/frontend-carbon-calculator#35]
**Describe the bug**
Cookie associated with a cross site resource

Address a warning from the javascript console:

A cookie associated with a cross-site resource at http://www.facebook.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.

**Comment by joseph280996** [comment]
this is issue of Firebase. The warning is for future change of chrome that may affect firebase connection. Once we deploy the website to a more secure platform with tls/ssl certificate, this will be gone. Since we are using Firebase as our service provider, this has to be deal with by Google and not us. 
 https://stackoverflow.com/questions/58686839/samesite-cookie-attribute-warning-isnt-getting-fixed
